[package]
name = "midwest_mainline"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "^0.4"
bendy = { version = "^0.3", features = ["serde", "serde_bytes"] }
serde = { version = "^1.0", features = ["derive"] }
serde_with = "^1.14"
juicy_bencode = "^0.1"
derive_more = "^0.99"

[dev-dependencies]
serde_json = "^1.0"
