[package]
name = "downloader"
version = "0.1.0"
edition = "2024"

[lib]
name = "downloader"
path = "src/lib.rs"

[[bin]]
name = "downloader"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
midwest_mainline = { path = "../dht"}
tokio-util = { version = "0.7.19", features = ["codec"] }
futures = "0.3.34"
tracing = "0.1.44"
juicy_bencode =  { path = "../../juicy_bencode" }
sha1 = "0.11.0"
rand = "0.10.2"
reqwest = "0.13.4"
url = "2.5.8"
bendy = "0.6.1"
anyhow = "1.0.104"
bitvec = "1.1.1"
derive_more = { version = "2.1.1", features = ["full"] }
crc32c = "0.6.8"
zerocopy = { version = "0.8.48", features = ["derive"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
dirs = "7.0.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
socket2 = "0.6.5"
public-ip = "0.2.2"
num-bigint = "0.5.1"
librqbit-utp = "0.7.0"
igd-next = { version = "0.17.1", features = ["aio_tokio"] }
crab_nat = "0.8.1"
netdev = "0.46.2"
