[package]
name = "downloader-gui"
version = "0.1.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
downloader = { path = "../../downloader" }
tauri = { version = "2.11.5", features = [] }
tauri-plugin-dialog = "2.7.3"
serde = { version = "1.0.229", features = ["derive"] }
rand = "0.10.2"
tauri-plugin-opener = "2.5.5"
tauri-plugin-notification = "2.4.0"
tokio = { version = "1.53", features = ["sync", "time"] }
tracing = "0.1.44"
